version: '3.1'
services:
  zhfd-mailnotify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zhfd-mailnotify
    volumes:
      - ./template:/usr/src/app/template
      - ./config.json:/usr/src/app/config.json